### ISSUE TITLE
QDMA: dmactl reg dump doesn't seem to work

### ISSUE THREAD

**Issue by hmaarrfk** [Xilinx/dma_ip_drivers#29] opened 2019-06-20 15:49 UTC
Once it starts to dump the config bar, all I see are 0s and Invalid bar number

```
CONFIG BAR #0

Invalid bar number

[      0] CFG_BLOCK_ID                                    0          0

```

**Comment by sujathabanoth-xlnx** [comment] 2021-01-29 11:48
We could not reproduce this issue on any latest driver versions at our end. regdump is working on all the supported OS and Kernel versions. Check your environment once. Closing the issue for now.

**Closed by sujathabanoth-xlnx** 2021-01-29 11:48 UTC

**Comment by hmaarrfk** [comment] 2021-01-30 04:51
It seems that maybe the issue has been resolved in a recent release.
